/* v282 : nouvelles voix et séquenceur. Pas de périphérique ni fichier personnel. */
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const R=path.resolve(__dirname,'..');let scenarios=0,assertions=0;
function ok(c,m){assertions++;assert.ok(c,m);}function eq(a,b,m){assertions++;assert.deepStrictEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)),m);}
function pres(a,b){ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);}
function test(n,f){try{f();scenarios++;console.log('ok '+n);}catch(e){console.error('FAUX '+n);throw e;}}
function env(sr=44100){
 const nodes=[],starts=[];
 class Param{constructor(v=0){this.value=v;this.ev=[];}setValueAtTime(v,t){ok(Number.isFinite(v)&&t>=0);this.ev.push({v,t,type:'set'});}linearRampToValueAtTime(v,t){ok(Number.isFinite(v)&&t>=0);this.ev.push({v,t,type:'lin'});}exponentialRampToValueAtTime(v,t){ok(v>0&&t>=0);this.ev.push({v,t,type:'exp'});}cancelScheduledValues(t){this.ev=this.ev.filter(e=>e.t<t);}cancelAndHoldAtTime(t){this.cancelScheduledValues(t);}}
 function node(type){const n={type,links:[],gain:new Param(1),frequency:new Param(440),detune:new Param(),offset:new Param(),Q:new Param(),playbackRate:new Param(1),connect(x){this.links.push(x);return x;},disconnect(){this.links=[];},start(t=0){this.debut=t;starts.push(this);},stop(t=0){this.fin=t;}};nodes.push(n);return n;}
 const ctx={sampleRate:sr,currentTime:0,createGain:()=>node('gain'),createOscillator:()=>node('osc'),createConstantSource:()=>node('const'),createBiquadFilter:()=>node('filtre'),createWaveShaper:()=>node('shaper'),createBufferSource:()=>node('buffer'),createBuffer(c,n,s){const ds=Array.from({length:c},()=>new Float32Array(n));return {duration:n/s,length:n,sampleRate:s,numberOfChannels:c,getChannelData:i=>ds[i]};}};
 const b={console,Math:Object.create(Math),Number,Float32Array,ctx,EUR_CAT:{},EUR_ORDRE:[],stepDur:()=>.1,maintenantAudio:()=>ctx.currentTime,
  eurGain:v=>{const n=ctx.createGain();n.gain.value=v;return n;},eurConst:v=>{const n=ctx.createConstantSource();n.offset.value=v;n.start();return n;},eurCourbe:f=>Float32Array.from({length:1025},(_,i)=>f(i/512-1))};
 vm.createContext(b);for(const f of ['461-voix-rave-eurorack.js','462-break32-eurorack.js'])vm.runInContext(fs.readFileSync(path.join(R,'page/js',f),'utf8'),b);
 function mod(type,ps={}){const def=b.EUR_CAT[type],m={id:1,type,p:{}};def.kns.forEach(k=>m.p[k[0]]=k[4]);Object.assign(m.p,ps);m.io=def.creer(m);return m;}
 return {b,ctx,mod,nodes,starts,buffers:()=>starts.filter(n=>n.type==='buffer'),oscs:()=>starts.filter(n=>n.type==='sine'||n.type==='sawtooth')};
}
function tick(m,i,t=.1){return m.recevoir(1+i*t,'clk');}
test('trois définitions uniques et ports déclarés',()=>{const e=env();eq(e.b.EUR_ORDRE,['corekick','bassrave','break32']);for(const [k,d] of Object.entries(e.b.EUR_CAT)){eq(new Set(d.kns.map(x=>x[0])).size,d.kns.length);const m=e.mod(k);eq(Object.keys(m.io.e).sort(),d.jacks.filter(x=>!x[2]).map(x=>x[0]).sort());eq(Object.keys(m.io.s).sort(),d.jacks.filter(x=>x[2]).map(x=>x[0]).sort());}});
test('paramètres invalides bornés',()=>{const e=env(),m=e.mod('corekick',{tune:NaN,dec:9000,niv:-2});eq([m.p.tune,m.p.dec,m.p.niv],[49,600,0]);const b=e.mod('break32',{len:Infinity,n3:200,v5:-1});eq([b.p.len,b.p.n3,b.p.v5],[32,16,0]);});
test('banque de seize tranches originales : finie, normalisée, inversée',()=>{const e=env(),c=e.b.EUR_BREAK32.banque();eq([c.avant.length,c.inverse.length],[16,16]);for(let i=0;i<16;i++){const a=c.avant[i].getChannelData(0),b=c.inverse[i].getChannelData(0);ok(a.every(x=>Number.isFinite(x)&&Math.abs(x)<=.801));ok(a.some(x=>Math.abs(x)>.001));for(let j=0;j<a.length;j+=127)pres(a[j],b[b.length-1-j]);}});
test('banque partagée par fréquence mais instances indépendantes',()=>{const e=env(),a=e.mod('break32'),b=e.mod('break32');tick(a,0);tick(b,0);ok(e.buffers()[0].buffer===e.buffers()[1].buffer);a.p.n1=4;eq(b.p.n1,1);const c=e.b.EUR_BREAK32.banque();e.ctx.sampleRate=48000;const d=e.b.EUR_BREAK32.banque();ok(c!==d);eq(d.sr,48000);});
test('32 pas avant le retour au premier',()=>{const e=env(),m=e.mod('break32');for(let i=0;i<65;i++){tick(m,i);eq(m.break32.pos,i%32);}eq(e.buffers().length,65);});
test('toutes les longueurs 1 à 32',()=>{for(let L=1;L<=32;L++){const e=env(),m=e.mod('break32',{len:L});for(let i=0;i<L*2+1;i++){tick(m,i);eq(m.break32.pos,i%L);}}});
test('raccourcir ne supprime pas les pas hors boucle',()=>{const e=env(),m=e.mod('break32',{len:3,n32:5,r32:4,v32:1,p32:37});for(let i=0;i<20;i++)tick(m,i);eq([m.p.n32,m.p.r32,m.p.v32,m.p.p32],[5,4,1,37]);});
test('silence coupe la tranche sans déclencher une voix',()=>{const e=env(),m=e.mod('break32',{n2:0});tick(m,0);tick(m,1);eq(e.buffers().length,1);eq(m.break32.pos,1);});
test('muet garde avancement et notes',()=>{const e=env(),m=e.mod('break32',{mute:1});for(let i=0;i<8;i++)tick(m,i);eq(e.buffers().length,0);eq(m.break32.pos,7);m.p.mute=0;tick(m,8);eq(e.buffers().length,1);eq(m.p.n8,8);});
test('probabilités 0 et 100 sans tirage inutile',()=>{const e=env(),m=e.mod('break32',{p1:0});let appels=0;e.b.Math.random=()=>{appels++;return .2;};tick(m,0);tick(m,1);eq(e.buffers().length,1);eq(appels,0);});
test('probabilité intermédiaire évaluée une seule fois par pas',()=>{const e=env(),m=e.mod('break32',{p1:30,r1:4});let n=0;e.b.Math.random=()=>{n++;return .4;};tick(m,0);eq([e.buffers().length,n],[0,1]);});
test('×2, ×3, ×4 programmés aux dates audio',()=>{for(let n=2;n<=4;n++){const e=env(),m=e.mod('break32',{r1:n});tick(m,0);eq(e.buffers().length,n);e.buffers().forEach((s,i)=>pres(s.debut,1+i*.1/n));}});
test('répétitions suivent l’intervalle reçu précédent',()=>{const e=env(),m=e.mod('break32',{r2:4});m.recevoir(1,'clk');m.recevoir(1.08,'clk');e.buffers().slice(1).forEach((s,i)=>pres(s.debut,1.08+i*.02));});
test('transposition change le débit, pas les départs',()=>{for(const pitch of [-12,0,12]){const e=env(),m=e.mod('break32',{pitch});tick(m,0);tick(m,1);pres(e.buffers()[0].playbackRate.value,Math.pow(2,pitch/12));pres(e.buffers()[1].debut,1.1);}});
test('inversion sélectionne la tranche renversée',()=>{const e=env(),m=e.mod('break32',{v1:1,n1:5});tick(m,0);ok(e.buffers()[0].buffer===e.b.EUR_BREAK32.banque().inverse[4]);});
test('dates invalides, doublées et anciennes ignorées',()=>{const e=env(),m=e.mod('break32');for(const t of [-1,NaN,Infinity])eq(m.recevoir(t,'clk'),null);eq(m.recevoir(1,'autre'),null);tick(m,0);for(const t of [.5,1])m.recevoir(t,'clk');eq([m.break32.pos,e.buffers().length],[0,1]);});
test('RST puis CLK au même instant repart du premier pas',()=>{const e=env(),m=e.mod('break32');tick(m,0);tick(m,1);m.recevoir(1.2,'rst');m.recevoir(1.19,'clk');eq(m.break32.pos,-1);m.recevoir(1.2,'clk');eq(m.break32.pos,0);});
test('STOP coupe les répétitions déjà programmées dans le futur',()=>{const e=env(),m=e.mod('break32',{r1:4});tick(m,0);e.ctx.currentTime=.99;m.arreter();ok(e.buffers().every(s=>s.fin<=.99));eq(m.break32.dates,[]);});
test('suppression du graphe ferme les voix et refuse les anciennes notifications',()=>{for(const type of ['break32','corekick']){const e=env(),m=e.mod(type);m.recevoir(1,type==='break32'?'clk':'trig');m.io.detruire();const n=e.starts.length;m.recevoir(2,type==='break32'?'clk':'trig');eq(e.starts.length,n);ok(!m.raveVoix.actif());eq(m.raveVoix.nombre(),0);}});
test('rendu hors ligne : pas d’historique graphique ni de panier non borné',()=>{const e=env();e.ctx.startRendering=()=>{};const m=e.mod('break32');for(let i=0;i<1000;i++)tick(m,i);eq(m.break32.dates,[]);ok(m.raveVoix.nombre()<10);});
test('CORE KICK respecte fondamentale, queue et niveau nul',()=>{const e=env(),m=e.mod('corekick',{tune:70,dec:100});m.recevoir(1,'trig');const o=e.starts.at(-1);pres(o.frequency.ev.at(-1).v,70);pres(o.fin,1.104);m.p.niv=0;m.recevoir(2,'trig');eq(e.starts.length,1);});
test('CORE KICK ignore doublons et coupe la queue au prochain départ',()=>{const e=env(),m=e.mod('corekick',{dec:600});m.recevoir(1,'trig');m.recevoir(1,'trig');eq(e.starts.length,1);m.recevoir(1.1,'trig');ok(e.starts[0].fin<=1.104);eq(e.starts.length,2);});
test('CORE KICK : distorsion centrée sur zéro dans les deux modes',()=>{for(const type of [0,.5,1]){const e=env(),m=e.mod('corekick',{type});m.recevoir(1,'trig');const s=e.nodes.find(n=>n.curve);pres(s.curve[512],0);for(let j=0;j<512;j+=23)pres(s.curve[j],-s.curve[1024-j]);eq(s.oversample,'4x');}});
test('BASS RAVE relie V/OCT aux trois oscillateurs',()=>{const e=env(),m=e.mod('bassrave');eq(m.io.e.voct.gain.value,1200);eq(m.io.e.voct.links.length,3);const os=e.nodes.filter(x=>['sawtooth','sine'].includes(x.type));eq(os.map(x=>x.frequency.value),[55,55,27.5]);});
test('BASS RAVE reese désaccorde seulement les dents, sub propre',()=>{const e=env(),m=e.mod('bassrave',{mode:1,det:1,oct:1});const os=e.nodes.filter(x=>['sawtooth','sine'].includes(x.type));eq(os.map(x=>x.frequency.value),[110,110,55]);eq(os.map(x=>x.detune.value),[-22,22,0]);});
test('BASS RAVE court et long gardent des dates valides',()=>{for(const dec of [20,52,330,750]){const e=env(),m=e.mod('bassrave',{dec});for(let i=0;i<40;i++)m.recevoir(1+i*.075,'trig');m.arreter();m.io.detruire();const n=e.starts.length;m.recevoir(10,'trig');eq(e.starts.length,n);}});
test('JSON conserve les nouveaux paramètres sans format séparé',()=>{for(const type of ['corekick','bassrave','break32']){const e=env(),m=e.mod(type),params=JSON.stringify(m.p);const n=e.mod(type,JSON.parse(params));eq(n.p,m.p);}});
console.log(`RAVE : ${scenarios} scénarios, ${assertions} assertions, 0 erreur.`);
